repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
        files: polyglot/
      - id: end-of-file-fixer
        files: polyglot/
      - id: mixed-line-ending
        files: polyglot/
  - repo: local
    hooks:
      - id: toml-fmt
        name: toml-fmt
        language: system
        entry: taplo fmt
      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: bash -c 'cargo fmt --manifest-path polyglot/piranha/Cargo.toml'
        types: [rust]
      - id: cargo-clippy
        name: cargo clippy
        language: system
        entry: bash -c 'cd polyglot/piranha && cargo clippy --fix --allow-staged'
        types: [rust]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-tabs
        files: polyglot/
      - id: remove-tabs
        files: polyglot/
      - id: insert-license
        files: \.rs$
        args:
          - --license-filepath
          - polyglot/piranha/license_header.txt
          - --comment-style
          - /*| | */
