name: Detect Changes

on:
  workflow_call:
    outputs:
      legacy:
        value: ${{ jobs.changes.outputs.legacy }}
      

jobs:
  # runs change detection
  # this job allows build to have a single if
  changes:
    runs-on: ubuntu-latest
    outputs:
      legacy: ${{ steps.filter.outputs.legacy }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: '.github/filters.yaml'
