# GitHub CI workflow for PiranhaJava

name: Legacy
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  detect:
    uses: ./.github/workflows/detect_changes.yml

  build_JDK:
    name: "Build Java (legacy)"
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ github.event_name == 'push' || needs.detect.outputs.legacy == 'true' }}
    steps:
      - name: Check out Piranha sources
        uses: actions/checkout@v2
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build and test using Gradle and Java
        uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: ./legacy/java
          wrapper-directory: ./legacy/java
          arguments: verGJF build

  build_JS:
    name: Build JS (legacy)
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ github.event_name == 'push' || needs.detect.outputs.legacy == 'true' }}
    env:
      HUSKY_SKIP_INSTALL: 1
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
        working-directory: "legacy/javascript"
      - run: npm test
        working-directory: "legacy/javascript"
      - run: npm test
        working-directory: "legacy/javascript"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Format
        run: |
          npm ci
          npm run check_format
        working-directory: "legacy/javascript"
      - uses: actions/checkout@v2
      - uses: hallee/eslint-action@1.0.3
        with:
          # GITHUB_TOKEN in forked repositories is read-only
          # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
          repo-token: ${{secrets.GITHUB_TOKEN}}
          source-root: legacy/javascript
