name: Legacy

on:
  pull_request:
    branches: [ master ]

jobs:
  detect:
    uses: ./.github/workflows/detect_changes.yml

  build_and_test_legacy:
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ needs.detect.outputs.legacy == 'false' }}

    steps:
      - run: 'echo "No changes to legacy implementations" '
